### ISSUE TITLE
Needs support for nested acronyms

### ISSUE THREAD

**Issue by guillochon** [bacook17/acronym#1]
Such as when an instrument name appears within another acronym.

**Comment by lgarrison** [comment]
```
$ ./acronym.py "Needs support for nested acronyms"
Finding Acronyms: 100%|████████████████████████████████████████████████████████████████| 100000/100000 [00:08<00:00, 11309.79it/s]
[...]
NAY	Needs support for nested AcronYms
```

**Comment by bacook17** [comment]
Can you give an example of input and expected result?

**Comment by guillochon** [comment]
I guess, if text exceeds a certain length, search for short acronyms first, then replace those parts of the text with the new acronyms, then run the algorithm again on the new string.

Probably good to also have a dictionary of acronyms that have already been used and reuse those when possible.

Australian Square Kilometer Array Pathfinder Rotation Measure and Polarisation Investigation -->
ASKAP Rotation Measure and Polarisation InvestigaTion -->
**ARMPIT**

**Comment by bacook17** [comment]
Successfully completed:
now includes a document "data/existing_acronyms.txt" which will be crowd-source edited to include common acronyms in current use. In combination with new "--nested" flag, can now search for acronyms after replacing existing acronyms.

Example of new result:
`acronym.py "Australian Square Kilometer Array Pathfinder Rotation Measure and Polarisation Investigation" --nested
[...]
ARMPIT	Askap Rotation Measure and Polarisation investIgaTion
[...]
`

**Comment by guillochon** [comment]
Potential sources of acronyms:
- https://www.cfa.harvard.edu/~gpetitpas/Links/Astroacro.html
- https://en.wikipedia.org/wiki/List_of_astronomy_acronyms
